[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio.workspace = true
futures.workspace = true
serde.workspace = true
serde_json.workspace = true
log.workspace = true

# local dependencies
udokai-shared.workspace = true
