[package]
name = "udokai-tui"
version = "0.0.1"
edition = "2021"
description = "The TUI for Udokai"
license = "MIT"

[dependencies]
ratatui = { version = "0.29.0", features = ["crossterm"] }
tui-input = "0.11.0"
log.workspace = true

# local
udokai-shared.workspace = true
