## Funzzy events file
# more details see: https://github.com/cristianoliveira/funzzy
#
# List here the tasks and the commands for this workflow
# then run `fzz` to start to work.

- name: run
  run: 
    - cargo build -p client
    - sleep 1
    - cargo build -p server
    - sleep 1
    - cargo build
    - touch .fzz/done
  change:
    - '**/*.rs'
    - '**/Cargo.*'
  ignore: 'target/**'
  run_on_init: true
