[package]
name = "dokai"
version = "0.1.0"
authors = ["cristianoliveira <contato@cristianoliveira.com.br>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
gui = { path = "gui" }
guiced = { path = "guiced" }
dioxus.workspace = true
dioxus-logger.workspace = true

[workspace.dependencies]
dioxus = { version = "0.5", features = ["desktop"] }
dioxus-logger = "0.5.1"

[workspace]
members = [ "gui" , "guiced"]
