[package]
name = "dokai"
version = "0.1.0"
authors = ["cristianoliveira <contato@cristianoliveira.com.br>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
# Internal pkgs
gui = { path = "gui" }
guiced = { path = "guiced" }
client = { path = "client" }
server = { path = "server" }

# External pkgs
dioxus.workspace = true
dioxus-logger.workspace = true
tokio.workspace = true
futures.workspace = true

[workspace.dependencies]
dioxus = { version = "0.5", features = ["desktop"] }
dioxus-logger = "0.5.1"
tokio = { version = "1", features = ["full"] }
futures = "0.3"

[workspace]
members = [ "client", "gui" , "guiced", "server"]
