[package]
name = "udokai-shared"
version = "0.0.1"
edition = "2021"
description = "The shared library for the Udokai project"
license = "MIT"

[dependencies]
log.workspace = true
log4rs.workspace = true
